default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: <%= ENV.fetch('POSTGRES_DB') %>

development:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST') %>
test:
  <<: *default
  database: geo_api_test
production:
  <<: *default
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
